PALETTE = {
    "bg": "#eef3f6",
    "surface": "#ffffff",
    "surface_alt": "#f6f9fb",
    "primary": "#0b5d7a",
    "primary_dark": "#08485f",
    "primary_soft": "#d9eaf1",
    "text": "#13212f",
    "muted": "#5b6a78",
    "border": "#c7d5df",
    "topbar_text": "#f1f7fb",
    "secondary_bg": "#e6eef3",
    "secondary_active": "#d6e3eb",
    "focus": "#ee9b00",
    "error_bg": "#ffe7ea",
    "error_text": "#8f1d2c",
    "success_bg": "#e8f6ee",
    "success_text": "#18603c",
    "warning_bg": "#fff4dd",
    "warning_text": "#8a5a00",
    "danger": "#b8475a",
    "danger_dark": "#963749",
}
